create table good (
    id int8 generated by default as identity,
    manufacturer varchar(255),
    "name" varchar(255),
    price numeric(19, 2),
    release_date timestamp,
    type varchar(255),
    primary key (id)
    )
