create table image (
    id int8 generated by default as identity,
    s3_key varchar(255),
    s3_uri varchar(255),
    good_id int8,
    primary key (id)
    );

alter table if exists image add constraint FKcb5ip32widtnbxj1urn28rmt4 foreign key (good_id) references good
